const NATION_FLAGS = {
  "Albania": "https://s1.fifaaddict.com/fo4/countries/1.png",
  "Algeria": "https://s1.fifaaddict.com/fo4/countries/97.png",
  "Angola": "https://s1.fifaaddict.com/fo4/countries/98.png",
  "Argentina": "https://s1.fifaaddict.com/fo4/countries/52.png",
  "Armenia": "https://s1.fifaaddict.com/fo4/countries/3.png",
  "Australia": "https://s1.fifaaddict.com/fo4/countries/195.png",
  "Austria": "https://s1.fifaaddict.com/fo4/countries/4.png",
  "Azerbaijan": "https://s1.fifaaddict.com/fo4/countries/5.png",
  "Belarus": "https://s1.fifaaddict.com/fo4/countries/6.png",
  "Belgium": "https://s1.fifaaddict.com/fo4/countries/7.png",
  "Benin": "https://s1.fifaaddict.com/fo4/countries/99.png",
  "Bolivia": "https://s1.fifaaddict.com/fo4/countries/53.png",
  "Bosnia Herzegovina": "https://s1.fifaaddict.com/fo4/countries/8.png",
  "Brazil": "https://s1.fifaaddict.com/fo4/countries/54.png",
  "Bulgaria": "https://s1.fifaaddict.com/fo4/countries/9.png",
  "Burkina Faso": "https://s1.fifaaddict.com/fo4/countries/101.png",
  "Cameroon": "https://s1.fifaaddict.com/fo4/countries/103.png",
  "Canada": "https://s1.fifaaddict.com/fo4/countries/70.png",
  "Cape Verde Islands": "https://s1.fifaaddict.com/fo4/countries/104.png",
  "Central African Rep": "https://s1.fifaaddict.com/fo4/countries/105.png",
  "Chile": "https://s1.fifaaddict.com/fo4/countries/55.png",
  "China PR": "https://s1.fifaaddict.com/fo4/countries/155.png",
  "Colombia": "https://s1.fifaaddict.com/fo4/countries/56.png",
  "Comoros": "https://s1.fifaaddict.com/fo4/countries/214.png",
  "Congo": "https://s1.fifaaddict.com/fo4/countries/107.png",
  "Costa Rica": "https://s1.fifaaddict.com/fo4/countries/72.png",
  "Croatia": "https://s1.fifaaddict.com/fo4/countries/10.png",
  "Cuba": "https://s1.fifaaddict.com/fo4/countries/73.png",
  "Curaçao": "https://s1.fifaaddict.com/fo4/countries/85.png",
  "Czech Republic": "https://s1.fifaaddict.com/fo4/countries/12.png",
  "Denmark": "https://s1.fifaaddict.com/fo4/countries/13.png",
  "Dominican Republic": "https://s1.fifaaddict.com/fo4/countries/207.png",
  "DR Congo": "https://s1.fifaaddict.com/fo4/countries/110.png",
  "Ecuador": "https://s1.fifaaddict.com/fo4/countries/57.png",
  "Egypt": "https://s1.fifaaddict.com/fo4/countries/111.png",
  "England": "https://s1.fifaaddict.com/fo4/countries/14.png",
  "Equatorial Guinea": "https://s1.fifaaddict.com/fo4/countries/112.png",
  "Estonia": "https://s1.fifaaddict.com/fo4/countries/208.png",
  "Fiji": "https://s1.fifaaddict.com/fo4/countries/197.png",
  "Finland": "https://s1.fifaaddict.com/fo4/countries/17.png",
  "France": "https://s1.fifaaddict.com/fo4/countries/18.png",
  "FYR Macedonia": "https://s1.fifaaddict.com/fo4/countries/19.png",
  "Gabon": "https://s1.fifaaddict.com/fo4/countries/115.png",
  "Gambia": "https://s1.fifaaddict.com/fo4/countries/116.png",
  "Georgia": "https://s1.fifaaddict.com/fo4/countries/20.png",
  "Germany": "https://s1.fifaaddict.com/fo4/countries/21.png",
  "Ghana": "https://s1.fifaaddict.com/fo4/countries/117.png",
  "Greece": "https://s1.fifaaddict.com/fo4/countries/22.png",
  "Guinea": "https://s1.fifaaddict.com/fo4/countries/118.png",
  "Guinea Bissau": "https://s1.fifaaddict.com/fo4/countries/119.png",
  "Haiti": "https://s1.fifaaddict.com/fo4/countries/80.png",
  "Holland": "https://s1.fifaaddict.com/fo4/countries/34.png",
  "Honduras": "https://s1.fifaaddict.com/fo4/countries/81.png",
  "Hong Kong": "https://s1.fifaaddict.com/fo4/countries/158.png",
  "Hungary": "https://s1.fifaaddict.com/fo4/countries/23.png",
  "Iceland": "https://s1.fifaaddict.com/fo4/countries/24.png",
  "Indonesia": "https://s1.fifaaddict.com/fo4/countries/160.png",
  "Iran": "https://s1.fifaaddict.com/fo4/countries/161.png",
  "Iraq": "https://s1.fifaaddict.com/fo4/countries/162.png",
  "Ireland Republic": "https://s1.fifaaddict.com/fo4/countries/25.png",
  "Israel": "https://s1.fifaaddict.com/fo4/countries/26.png",
  "Italy": "https://s1.fifaaddict.com/fo4/countries/27.png",
  "Ivory Coast": "https://s1.fifaaddict.com/fo4/countries/108.png",
  "Jamaica": "https://s1.fifaaddict.com/fo4/countries/82.png",
  "Japan": "https://s1.fifaaddict.com/fo4/countries/163.png",
  "Jordan": "https://s1.fifaaddict.com/fo4/countries/164.png",
  "Kazakhstan": "https://s1.fifaaddict.com/fo4/countries/165.png",
  "Kenya": "https://s1.fifaaddict.com/fo4/countries/120.png",
  "Korea Republic": "https://s1.fifaaddict.com/fo4/countries/167.png",
  "Kosova": "https://s1.fifaaddict.com/fo4/countries/219.png",
  "Libya": "https://s1.fifaaddict.com/fo4/countries/123.png",
  "Lithuania": "https://s1.fifaaddict.com/fo4/countries/30.png",
  "Luxembourg": "https://s1.fifaaddict.com/fo4/countries/31.png",
  "Madagascar": "https://s1.fifaaddict.com/fo4/countries/124.png",
  "Mali": "https://s1.fifaaddict.com/fo4/countries/126.png",
  "Mauritania": "https://s1.fifaaddict.com/fo4/countries/127.png",
  "Mexico": "https://s1.fifaaddict.com/fo4/countries/83.png",
  "Moldova": "https://s1.fifaaddict.com/fo4/countries/33.png",
  "Montenegro": "https://s1.fifaaddict.com/fo4/countries/15.png",
  "Morocco": "https://s1.fifaaddict.com/fo4/countries/129.png",
  "Mozambique": "https://s1.fifaaddict.com/fo4/countries/130.png",
  "Namibia": "https://s1.fifaaddict.com/fo4/countries/131.png",
  "New Zealand": "https://s1.fifaaddict.com/fo4/countries/198.png",
  "Nigeria": "https://s1.fifaaddict.com/fo4/countries/133.png",
  "Northern Ireland": "https://s1.fifaaddict.com/fo4/countries/35.png",
  "Norway": "https://s1.fifaaddict.com/fo4/countries/36.png",
  "Panama": "https://s1.fifaaddict.com/fo4/countries/87.png",
  "Paraguay": "https://s1.fifaaddict.com/fo4/countries/58.png",
  "Peru": "https://s1.fifaaddict.com/fo4/countries/59.png",
  "Poland": "https://s1.fifaaddict.com/fo4/countries/37.png",
  "Portugal": "https://s1.fifaaddict.com/fo4/countries/38.png",
  "Qatar": "https://s1.fifaaddict.com/fo4/countries/182.png",
  "Romania": "https://s1.fifaaddict.com/fo4/countries/39.png",
  "Russia": "https://s1.fifaaddict.com/fo4/countries/40.png",
  "Saudi Arabia": "https://s1.fifaaddict.com/fo4/countries/183.png",
  "Scotland": "https://s1.fifaaddict.com/fo4/countries/42.png",
  "Senegal": "https://s1.fifaaddict.com/fo4/countries/136.png",
  "Serbia": "https://s1.fifaaddict.com/fo4/countries/51.png",
  "Sierra Leone": "https://s1.fifaaddict.com/fo4/countries/138.png",
  "Slovakia": "https://s1.fifaaddict.com/fo4/countries/43.png",
  "Slovenia": "https://s1.fifaaddict.com/fo4/countries/44.png",
  "South Africa": "https://s1.fifaaddict.com/fo4/countries/140.png",
  "Spain": "https://s1.fifaaddict.com/fo4/countries/45.png",
  "Suriname": "https://s1.fifaaddict.com/fo4/countries/92.png",
  "Sweden": "https://s1.fifaaddict.com/fo4/countries/46.png",
  "Switzerland": "https://s1.fifaaddict.com/fo4/countries/47.png",
  "Syria": "https://s1.fifaaddict.com/fo4/countries/186.png",
  "Thailand": "https://s1.fifaaddict.com/fo4/countries/188.png",
  "Togo": "https://s1.fifaaddict.com/fo4/countries/144.png",
  "Trinidad and Tobago": "https://s1.fifaaddict.com/fo4/countries/93.png",
  "Tunisia": "https://s1.fifaaddict.com/fo4/countries/145.png",
  "Turkey": "https://s1.fifaaddict.com/fo4/countries/48.png",
  "Ukraine": "https://s1.fifaaddict.com/fo4/countries/49.png",
  "United Arab Emirates": "https://s1.fifaaddict.com/fo4/countries/190.png",
  "United States": "https://s1.fifaaddict.com/fo4/countries/95.png",
  "Uruguay": "https://s1.fifaaddict.com/fo4/countries/60.png",
  "Uzbekistan": "https://s1.fifaaddict.com/fo4/countries/191.png",
  "Venezuela": "https://s1.fifaaddict.com/fo4/countries/61.png",
  "Vietnam": "https://s1.fifaaddict.com/fo4/countries/192.png",
  "Wales": "https://s1.fifaaddict.com/fo4/countries/50.png",
  "Zambia": "https://s1.fifaaddict.com/fo4/countries/147.png",
  "Zimbabwe": "https://s1.fifaaddict.com/fo4/countries/148.png"
};

const LEAGUE_LOGOS = {
  "Argentina Liga Profesional de Fútbol": "https://s1.fifaaddict.com/fo4/league/dark/d353.png",
  "Australia A-League Men": "https://s1.fifaaddict.com/fo4/league/dark/d351.png",
  "Austria Bundesliga": "https://s1.fifaaddict.com/fo4/league/dark/d80.png",
  "Belgium Pro League": "https://s1.fifaaddict.com/fo4/league/dark/d4.png",
  "China PR Super League": "https://s1.fifaaddict.com/fo4/league/dark/d2012.png",
  "Denmark Superliga": "https://s1.fifaaddict.com/fo4/league/dark/d1.png",
  "England Championship": "https://s1.fifaaddict.com/fo4/league/dark/d14.png",
  "England League One": "https://s1.fifaaddict.com/fo4/league/dark/d61.png",
  "England League Two": "https://s1.fifaaddict.com/fo4/league/dark/d61.png",
  "England Premier League": "https://s1.fifaaddict.com/fo4/league/dark/d13.png",
  "France Ligue 1": "https://s1.fifaaddict.com/fo4/league/dark/d16.png",
  "France Ligue 2": "https://s1.fifaaddict.com/fo4/league/dark/d17.png",
  "Germany 2. Bundesliga": "https://s1.fifaaddict.com/fo4/league/dark/d20.png",
  "Germany 3. Liga": "https://s1.fifaaddict.com/fo4/league/dark/d2076.png",
  "Germany Bundesliga": "https://s1.fifaaddict.com/fo4/league/dark/d19.png",
  "Italy Serie A": "https://s1.fifaaddict.com/fo4/league/dark/d31.png",
  "Italy Serie B": "https://s1.fifaaddict.com/fo4/league/dark/d32.png",
  "Korea K-League Challenge": "https://s1.fifaaddict.com/fo4/league/dark/d2111.png",
  "Korea Republic K League 1": "https://s1.fifaaddict.com/fo4/league/dark/d83.png",
  "Netherlands Eredivisie": "https://s1.fifaaddict.com/fo4/league/dark/d10.png",
  "Norway Eliteserien": "https://s1.fifaaddict.com/fo4/league/dark/d41.png",
  "Poland Ekstraklasa": "https://s1.fifaaddict.com/fo4/league/dark/d66.png",
  "Portugal Primeira Liga": "https://s1.fifaaddict.com/fo4/league/dark/d308.png",
  "Rest of World": "https://s1.fifaaddict.com/fo4/league/dark/d76.png",
  "Saudi Arabia Pro League": "https://s1.fifaaddict.com/fo4/league/dark/d350.png",
  "Scotland Premiership": "https://s1.fifaaddict.com/fo4/league/dark/d50.png",
  "Spain La Liga": "https://s1.fifaaddict.com/fo4/league/dark/d53.png",
  "Spain La Liga 2": "https://s1.fifaaddict.com/fo4/league/dark/d54.png",
  "Sweden Allsvenskan": "https://s1.fifaaddict.com/fo4/league/dark/d56.png",
  "Switzerland Super League": "https://s1.fifaaddict.com/fo4/league/dark/d189.png",
  "Türkiye Süper Lig": "https://s1.fifaaddict.com/fo4/league/dark/d68.png",
  "United States Major League Soccer": "https://s1.fifaaddict.com/fo4/league/dark/d39.png",
  "World League": "https://s1.fifaaddict.com/fo4/league/dark/d2028.png"
};

const CLUB_CRESTS = {
  "1. FC Heidenheim 1846": "https://s1.fifaaddict.com/fo4/crests/dark/d111235.png",
  "1. FC Kaiserslautern": "https://s1.fifaaddict.com/fo4/crests/dark/d29.png",
  "1. FC Köln": "https://s1.fifaaddict.com/fo4/crests/dark/d31.png",
  "1. FC Nürnberg": "https://s1.fifaaddict.com/fo4/crests/dark/d171.png",
  "1. FC Union Berlin": "https://s1.fifaaddict.com/fo4/crests/dark/d1831.png",
  "1. FSV Mainz 05": "https://s1.fifaaddict.com/fo4/crests/dark/d169.png",
  "19 New Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d114601.png",
  "20 New Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d114890.png",
  "20 TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d114850.png",
  "21 New Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d115649.png",
  "21 TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d115427.png",
  "21 TOTY": "https://s1.fifaaddict.com/fo4/crests/dark/d115178.png",
  "21 TOTY Nominee": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "21TOTY Nominee": "https://s1.fifaaddict.com/fo4/crests/dark/d115179.png",
  "22 HEROES": "https://s1.fifaaddict.com/fo4/crests/dark/d115391.png",
  "22 New Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d130185.png",
  "22 TOTY": "https://s1.fifaaddict.com/fo4/crests/dark/d115642.png",
  "22 TOTY Nominee": "https://s1.fifaaddict.com/fo4/crests/dark/d115643.png",
  "22TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d115396.png",
  "23 Hard Worker": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "23 HEROES": "https://s1.fifaaddict.com/fo4/crests/dark/d130203.png",
  "23 New Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d130280.png",
  "23 TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "23 TOTY Nominee": "https://s1.fifaaddict.com/fo4/crests/dark/d130082.png",
  "23TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d130072.png",
  "24 Energetic": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "24 Energetic Player": "https://s1.fifaaddict.com/fo4/crests/dark/d130386.png",
  "24 HEROES": "https://s1.fifaaddict.com/fo4/crests/dark/d130294.png",
  "24 TOTY": "https://s1.fifaaddict.com/fo4/crests/dark/d130299.png",
  "24 TOTY Nominee": "https://s1.fifaaddict.com/fo4/crests/dark/d130266.png",
  "24TOTS": "https://s1.fifaaddict.com/fo4/crests/dark/d130334.png",
  "24VB": "https://s1.fifaaddict.com/fo4/crests/dark/d130318.png",
  "25 FC SPEAR": "https://s1.fifaaddict.com/fo4/crests/dark/d130513.png",
  "25 FCO Super Champions League": "https://s1.fifaaddict.com/fo4/crests/dark/d130520.png",
  "25 HEROES": "https://s1.fifaaddict.com/fo4/crests/dark/d130425.png",
  "25 SHIELD UTD": "https://s1.fifaaddict.com/fo4/crests/dark/d130514.png",
  "25VB": "https://s1.fifaaddict.com/fo4/crests/dark/d130466.png",
  "26 HEROES": "https://s1.fifaaddict.com/fo4/crests/dark/d130565.png",
  "AaB": "https://s1.fifaaddict.com/fo4/crests/dark/d820.png",
  "Aberdeen": "https://s1.fifaaddict.com/fo4/crests/dark/d77.png",
  "AC Ajaccio": "https://s1.fifaaddict.com/fo4/crests/dark/d614.png",
  "AC Sparta Praha": "https://s1.fifaaddict.com/fo4/crests/dark/d267.png",
  "AD Ceuta FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1894.png",
  "Adana Demirspor": "https://s1.fifaaddict.com/fo4/crests/dark/d101016.png",
  "Adelaide United": "https://s1.fifaaddict.com/fo4/crests/dark/d111393.png",
  "AEK Athens": "https://s1.fifaaddict.com/fo4/crests/dark/d278.png",
  "AFC Bournemouth": "https://s1.fifaaddict.com/fo4/crests/dark/d1943.png",
  "AGF": "https://s1.fifaaddict.com/fo4/crests/dark/d271.png",
  "AIK": "https://s1.fifaaddict.com/fo4/crests/dark/d433.png",
  "AJ Auxerre": "https://s1.fifaaddict.com/fo4/crests/dark/d57.png",
  "Ajax": "https://s1.fifaaddict.com/fo4/crests/dark/d245.png",
  "Al Ahli": "https://s1.fifaaddict.com/fo4/crests/dark/d112387.png",
  "Al Ain FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111701.png",
  "Al Ettifaq": "https://s1.fifaaddict.com/fo4/crests/dark/d112096.png",
  "Al Fateh": "https://s1.fifaaddict.com/fo4/crests/dark/d112390.png",
  "Al Fayha": "https://s1.fifaaddict.com/fo4/crests/dark/d113057.png",
  "Al Hazem": "https://s1.fifaaddict.com/fo4/crests/dark/d113222.png",
  "Al Hilal": "https://s1.fifaaddict.com/fo4/crests/dark/d605.png",
  "Al Ittihad": "https://s1.fifaaddict.com/fo4/crests/dark/d607.png",
  "Al Khaleej": "https://s1.fifaaddict.com/fo4/crests/dark/d112883.png",
  "Al Kholood": "https://s1.fifaaddict.com/fo4/crests/dark/d131735.png",
  "Al Najmah": "https://s1.fifaaddict.com/fo4/crests/dark/d115892.png",
  "Al Nassr": "https://s1.fifaaddict.com/fo4/crests/dark/d112139.png",
  "Al Okhdood": "https://s1.fifaaddict.com/fo4/crests/dark/d113060.png",
  "Al Orobah": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "Al Qadsiah": "https://s1.fifaaddict.com/fo4/crests/dark/d112391.png",
  "Al Raed": "https://s1.fifaaddict.com/fo4/crests/dark/d112392.png",
  "Al Riyadh": "https://s1.fifaaddict.com/fo4/crests/dark/d113037.png",
  "Al Shabab": "https://s1.fifaaddict.com/fo4/crests/dark/d111674.png",
  "Al Taawoun": "https://s1.fifaaddict.com/fo4/crests/dark/d112393.png",
  "Al Wehda": "https://s1.fifaaddict.com/fo4/crests/dark/d112408.png",
  "Albacete Balompié": "https://s1.fifaaddict.com/fo4/crests/dark/d1854.png",
  "Alemannia Aachen": "https://s1.fifaaddict.com/fo4/crests/dark/d1826.png",
  "Almere City FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111380.png",
  "Amiens SC": "https://s1.fifaaddict.com/fo4/crests/dark/d1816.png",
  "Angers SCO": "https://s1.fifaaddict.com/fo4/crests/dark/d1530.png",
  "Antalyaspor": "https://s1.fifaaddict.com/fo4/crests/dark/d741.png",
  "Apoel FC": "https://s1.fifaaddict.com/fo4/crests/dark/d100135.png",
  "Argentinos Juniors": "https://s1.fifaaddict.com/fo4/crests/dark/d111019.png",
  "Arsenal": "https://s1.fifaaddict.com/fo4/crests/dark/d1.png",
  "AS Monaco": "https://s1.fifaaddict.com/fo4/crests/dark/d69.png",
  "AS Nancy Lorraine": "https://s1.fifaaddict.com/fo4/crests/dark/d1823.png",
  "AS Roma": "https://s1.fifaaddict.com/fo4/crests/dark/d52.png",
  "AS Saint-Étienne": "https://s1.fifaaddict.com/fo4/crests/dark/d1819.png",
  "Aston Villa": "https://s1.fifaaddict.com/fo4/crests/dark/d2.png",
  "Atakaş Hatayspor": "https://s1.fifaaddict.com/fo4/crests/dark/d101028.png",
  "Athletic Club": "https://s1.fifaaddict.com/fo4/crests/dark/d448.png",
  "Atlanta United": "https://s1.fifaaddict.com/fo4/crests/dark/d112885.png",
  "Atlético de Madrid": "https://s1.fifaaddict.com/fo4/crests/dark/d240.png",
  "Atlético Nacional": "https://s1.fifaaddict.com/fo4/crests/dark/d101100.png",
  "Atlético Tucumán": "https://s1.fifaaddict.com/fo4/crests/dark/d111708.png",
  "Auckland Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d131739.png",
  "Austin FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114161.png",
  "Avellino": "https://s1.fifaaddict.com/fo4/crests/dark/d2038.png",
  "Avs Futebol SAD": "https://s1.fifaaddict.com/fo4/crests/dark/d131463.png",
  "AVS Futebol SAD": "https://s1.fifaaddict.com/fo4/crests/dark/d131463.png",
  "AZ": "https://s1.fifaaddict.com/fo4/crests/dark/d1906.png",
  "Back to Back": "https://s1.fifaaddict.com/fo4/crests/dark/d115635.png",
  "Ballon d'Or": "https://s1.fifaaddict.com/fo4/crests/dark/d130391.png",
  "Bari": "https://s1.fifaaddict.com/fo4/crests/dark/d1848.png",
  "Barracas Central": "https://s1.fifaaddict.com/fo4/crests/dark/d113044.png",
  "Bayer 04 Leverkusen": "https://s1.fifaaddict.com/fo4/crests/dark/d32.png",
  "Beijing Guoan Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d111768.png",
  "Belgrano de Córdoba": "https://s1.fifaaddict.com/fo4/crests/dark/d111022.png",
  "Bergamo Calcio": "https://s1.fifaaddict.com/fo4/crests/dark/d115845.png",
  "Beşiktaş JK": "https://s1.fifaaddict.com/fo4/crests/dark/d327.png",
  "Best of Europe": "https://s1.fifaaddict.com/fo4/crests/dark/d114745.png",
  "Best of Europe 2021": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "Best of Europe 21": "https://s1.fifaaddict.com/fo4/crests/dark/d115626.png",
  "Best of World Cup": "https://s1.fifaaddict.com/fo4/crests/dark/d130178.png",
  "Birmingham City": "https://s1.fifaaddict.com/fo4/crests/dark/d88.png",
  "BK Häcken": "https://s1.fifaaddict.com/fo4/crests/dark/d711.png",
  "Blackburn Rovers": "https://s1.fifaaddict.com/fo4/crests/dark/d3.png",
  "Boavista FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1898.png",
  "Boca Juniors": "https://s1.fifaaddict.com/fo4/crests/dark/d1877.png",
  "Bologna": "https://s1.fifaaddict.com/fo4/crests/dark/d189.png",
  "Borussia Dortmund": "https://s1.fifaaddict.com/fo4/crests/dark/d22.png",
  "Borussia Mönchengladbach": "https://s1.fifaaddict.com/fo4/crests/dark/d23.png",
  "Brentford": "https://s1.fifaaddict.com/fo4/crests/dark/d1925.png",
  "Brighton & Hove Albion": "https://s1.fifaaddict.com/fo4/crests/dark/d1808.png",
  "Brisbane Roar": "https://s1.fifaaddict.com/fo4/crests/dark/d111395.png",
  "Bristol City": "https://s1.fifaaddict.com/fo4/crests/dark/d1919.png",
  "Bristol Rovers": "https://s1.fifaaddict.com/fo4/crests/dark/d1962.png",
  "Brøndby IF": "https://s1.fifaaddict.com/fo4/crests/dark/d269.png",
  "BSC Young Boys": "https://s1.fifaaddict.com/fo4/crests/dark/d900.png",
  "Bucheon FC 1995": "https://s1.fifaaddict.com/fo4/crests/dark/d112554.png",
  "Burgos CF": "https://s1.fifaaddict.com/fo4/crests/dark/d10846.png",
  "Burnley": "https://s1.fifaaddict.com/fo4/crests/dark/d1796.png",
  "C.O.C": "https://s1.fifaaddict.com/fo4/crests/dark/d114379.png",
  "CA Osasuna": "https://s1.fifaaddict.com/fo4/crests/dark/d479.png",
  "Cádiz CF": "https://s1.fifaaddict.com/fo4/crests/dark/d1968.png",
  "Cagliari": "https://s1.fifaaddict.com/fo4/crests/dark/d1842.png",
  "Calcio Padova": "https://s1.fifaaddict.com/fo4/crests/dark/d110912.png",
  "Cambridge United": "https://s1.fifaaddict.com/fo4/crests/dark/d1944.png",
  "Cangzhou Mighty Lions Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d112985.png",
  "Captain": "https://s1.fifaaddict.com/fo4/crests/dark/d115436.png",
  "Cardiff City": "https://s1.fifaaddict.com/fo4/crests/dark/d1961.png",
  "Carrarese Calcio 1908": "https://s1.fifaaddict.com/fo4/crests/dark/d112493.png",
  "Casa Pia AC": "https://s1.fifaaddict.com/fo4/crests/dark/d114510.png",
  "Catanzaro": "https://s1.fifaaddict.com/fo4/crests/dark/d110908.png",
  "Çaykur Rizespor": "https://s1.fifaaddict.com/fo4/crests/dark/d101037.png",
  "CD Castellón": "https://s1.fifaaddict.com/fo4/crests/dark/d100852.png",
  "CD Eldense": "https://s1.fifaaddict.com/fo4/crests/dark/d131110.png",
  "CD Leganés": "https://s1.fifaaddict.com/fo4/crests/dark/d100888.png",
  "CD Mirandés": "https://s1.fifaaddict.com/fo4/crests/dark/d110069.png",
  "CD Nacional": "https://s1.fifaaddict.com/fo4/crests/dark/d1891.png",
  "CD Tenerife": "https://s1.fifaaddict.com/fo4/crests/dark/d260.png",
  "CD Tondela": "https://s1.fifaaddict.com/fo4/crests/dark/d112516.png",
  "Celtic": "https://s1.fifaaddict.com/fo4/crests/dark/d78.png",
  "Central Coast Mariners": "https://s1.fifaaddict.com/fo4/crests/dark/d111396.png",
  "Century Club": "https://s1.fifaaddict.com/fo4/crests/dark/d130086.png",
  "Cercle Brugge KSV": "https://s1.fifaaddict.com/fo4/crests/dark/d1750.png",
  "Cesena": "https://s1.fifaaddict.com/fo4/crests/dark/d110915.png",
  "CF Montréal": "https://s1.fifaaddict.com/fo4/crests/dark/d111139.png",
  "Champions of Europe": "https://s1.fifaaddict.com/fo4/crests/dark/d130371.png",
  "Changchun Yatai Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d111769.png",
  "Charlotte FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114640.png",
  "Charlton Athletic": "https://s1.fifaaddict.com/fo4/crests/dark/d89.png",
  "Chelsea": "https://s1.fifaaddict.com/fo4/crests/dark/d5.png",
  "Chelsea FC Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d115628.png",
  "Chengdu Rongcheng Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d116360.png",
  "Cheonan City FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114653.png",
  "Chicago Fire Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d693.png",
  "Chungnam Asan FC": "https://s1.fifaaddict.com/fo4/crests/dark/d112559.png",
  "Clermont Foot 63": "https://s1.fifaaddict.com/fo4/crests/dark/d1815.png",
  "Club Atlético Banfield": "https://s1.fifaaddict.com/fo4/crests/dark/d110404.png",
  "Club Atlético Central Córdoba": "https://s1.fifaaddict.com/fo4/crests/dark/d112965.png",
  "Club Atlético Huracán": "https://s1.fifaaddict.com/fo4/crests/dark/d111711.png",
  "Club Atlético Independiente": "https://s1.fifaaddict.com/fo4/crests/dark/d110093.png",
  "Club Atlético Lanús": "https://s1.fifaaddict.com/fo4/crests/dark/d110395.png",
  "Club Atlético Platense": "https://s1.fifaaddict.com/fo4/crests/dark/d112689.png",
  "Club Atlético San Martín": "https://s1.fifaaddict.com/fo4/crests/dark/d111713.png",
  "Club Atlético Sarmiento": "https://s1.fifaaddict.com/fo4/crests/dark/d112713.png",
  "Club Atlético Talleres": "https://s1.fifaaddict.com/fo4/crests/dark/d112670.png",
  "Club Atlético Tigre": "https://s1.fifaaddict.com/fo4/crests/dark/d111715.png",
  "Club Brugge": "https://s1.fifaaddict.com/fo4/crests/dark/d231.png",
  "Colorado Rapids": "https://s1.fifaaddict.com/fo4/crests/dark/d694.png",
  "Columbus Crew": "https://s1.fifaaddict.com/fo4/crests/dark/d687.png",
  "Como 1907": "https://s1.fifaaddict.com/fo4/crests/dark/d1745.png",
  "Continental Heroes": "https://s1.fifaaddict.com/fo4/crests/dark/d130492.png",
  "Córdoba CF": "https://s1.fifaaddict.com/fo4/crests/dark/d1867.png",
  "Corendon Alanyaspor": "https://s1.fifaaddict.com/fo4/crests/dark/d113142.png",
  "Cosenza": "https://s1.fifaaddict.com/fo4/crests/dark/d112168.png",
  "Coventry City": "https://s1.fifaaddict.com/fo4/crests/dark/d1800.png",
  "Cracovia": "https://s1.fifaaddict.com/fo4/crests/dark/d110747.png",
  "Crawley Town": "https://s1.fifaaddict.com/fo4/crests/dark/d110890.png",
  "Cremonese": "https://s1.fifaaddict.com/fo4/crests/dark/d111434.png",
  "Crystal Palace": "https://s1.fifaaddict.com/fo4/crests/dark/d1799.png",
  "CS Independiente Rivadavia": "https://s1.fifaaddict.com/fo4/crests/dark/d111020.png",
  "Cultural Leonesa": "https://s1.fifaaddict.com/fo4/crests/dark/d15012.png",
  "D.C. United": "https://s1.fifaaddict.com/fo4/crests/dark/d688.png",
  "Daegu FC": "https://s1.fifaaddict.com/fo4/crests/dark/d2056.png",
  "Daejeon HanaCitizen FC": "https://s1.fifaaddict.com/fo4/crests/dark/d980.png",
  "Dalian Young Boy Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d132305.png",
  "Damac": "https://s1.fifaaddict.com/fo4/crests/dark/d113217.png",
  "Decade": "https://s1.fifaaddict.com/fo4/crests/dark/d130262.png",
  "Defensa y Justicia": "https://s1.fifaaddict.com/fo4/crests/dark/d111710.png",
  "Deportivo Alavés": "https://s1.fifaaddict.com/fo4/crests/dark/d463.png",
  "Derby County": "https://s1.fifaaddict.com/fo4/crests/dark/d91.png",
  "Djurgårdens IF": "https://s1.fifaaddict.com/fo4/crests/dark/d710.png",
  "Doncaster Rovers": "https://s1.fifaaddict.com/fo4/crests/dark/d142.png",
  "Dramatic Comebacks": "https://s1.fifaaddict.com/fo4/crests/dark/d130491.png",
  "DSC Arminia Bielefeld": "https://s1.fifaaddict.com/fo4/crests/dark/d159.png",
  "Dundee FC": "https://s1.fifaaddict.com/fo4/crests/dark/d180.png",
  "Dynamo Kyiv": "https://s1.fifaaddict.com/fo4/crests/dark/d101047.png",
  "Eintracht Braunschweig": "https://s1.fifaaddict.com/fo4/crests/dark/d110500.png",
  "Eintracht Frankfurt": "https://s1.fifaaddict.com/fo4/crests/dark/d1824.png",
  "Elche CF": "https://s1.fifaaddict.com/fo4/crests/dark/d468.png",
  "Empoli": "https://s1.fifaaddict.com/fo4/crests/dark/d1746.png",
  "EMS Yapı Sivasspor": "https://s1.fifaaddict.com/fo4/crests/dark/d101041.png",
  "En Avant Guingamp": "https://s1.fifaaddict.com/fo4/crests/dark/d62.png",
  "ESTAC Troyes": "https://s1.fifaaddict.com/fo4/crests/dark/d294.png",
  "Estoril Praia": "https://s1.fifaaddict.com/fo4/crests/dark/d10020.png",
  "Estrela Amadora": "https://s1.fifaaddict.com/fo4/crests/dark/d718.png",
  "Estudiantes de La Plata": "https://s1.fifaaddict.com/fo4/crests/dark/d101083.png",
  "EU24": "https://s1.fifaaddict.com/fo4/crests/dark/d130354.png",
  "European Best Stars": "https://s1.fifaaddict.com/fo4/crests/dark/d115438.png",
  "Everton": "https://s1.fifaaddict.com/fo4/crests/dark/d7.png",
  "F.C. København": "https://s1.fifaaddict.com/fo4/crests/dark/d819.png",
  "Fatih Karagümrük SK": "https://s1.fifaaddict.com/fo4/crests/dark/d111117.png",
  "FC Alverca": "https://s1.fifaaddict.com/fo4/crests/dark/d717.png",
  "FC Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d130256.png",
  "FC Annecy": "https://s1.fifaaddict.com/fo4/crests/dark/d131447.png",
  "FC Anyang": "https://s1.fifaaddict.com/fo4/crests/dark/d112555.png",
  "FC Arouca": "https://s1.fifaaddict.com/fo4/crests/dark/d112513.png",
  "FC Augsburg": "https://s1.fifaaddict.com/fo4/crests/dark/d100409.png",
  "FC Barcelona": "https://s1.fifaaddict.com/fo4/crests/dark/d241.png",
  "FC Basel 1893": "https://s1.fifaaddict.com/fo4/crests/dark/d896.png",
  "FC Bayern München": "https://s1.fifaaddict.com/fo4/crests/dark/d21.png",
  "FC Blau-Weiss Linz": "https://s1.fifaaddict.com/fo4/crests/dark/d110720.png",
  "FC Cartagena": "https://s1.fifaaddict.com/fo4/crests/dark/d100851.png",
  "FC Cincinnati": "https://s1.fifaaddict.com/fo4/crests/dark/d113149.png",
  "FC Dallas": "https://s1.fifaaddict.com/fo4/crests/dark/d695.png",
  "FC Energie Cottbus": "https://s1.fifaaddict.com/fo4/crests/dark/d162.png",
  "FC Erzgebirge Aue": "https://s1.fifaaddict.com/fo4/crests/dark/d506.png",
  "FC Famalicão": "https://s1.fifaaddict.com/fo4/crests/dark/d112809.png",
  "FC Groningen": "https://s1.fifaaddict.com/fo4/crests/dark/d1915.png",
  "FC Ingolstadt 04": "https://s1.fifaaddict.com/fo4/crests/dark/d111239.png",
  "FC Lausanne-Sport": "https://s1.fifaaddict.com/fo4/crests/dark/d1862.png",
  "FC Lorient": "https://s1.fifaaddict.com/fo4/crests/dark/d217.png",
  "FC Lugano": "https://s1.fifaaddict.com/fo4/crests/dark/d10032.png",
  "FC Metz": "https://s1.fifaaddict.com/fo4/crests/dark/d68.png",
  "FC Midtjylland": "https://s1.fifaaddict.com/fo4/crests/dark/d1516.png",
  "FC Nantes": "https://s1.fifaaddict.com/fo4/crests/dark/d71.png",
  "FC Nordsjælland": "https://s1.fifaaddict.com/fo4/crests/dark/d1788.png",
  "FC Pohang Steelers": "https://s1.fifaaddict.com/fo4/crests/dark/d1474.png",
  "FC Porto": "https://s1.fifaaddict.com/fo4/crests/dark/d236.png",
  "FC Red Bull Salzburg": "https://s1.fifaaddict.com/fo4/crests/dark/d191.png",
  "FC Schalke 04": "https://s1.fifaaddict.com/fo4/crests/dark/d34.png",
  "FC Seoul": "https://s1.fifaaddict.com/fo4/crests/dark/d982.png",
  "FC Sion": "https://s1.fifaaddict.com/fo4/crests/dark/d110770.png",
  "FC St. Gallen 1879": "https://s1.fifaaddict.com/fo4/crests/dark/d898.png",
  "FC St. Pauli": "https://s1.fifaaddict.com/fo4/crests/dark/d110329.png",
  "FC Twente": "https://s1.fifaaddict.com/fo4/crests/dark/d1908.png",
  "FC Utrecht": "https://s1.fifaaddict.com/fo4/crests/dark/d1903.png",
  "FC Viktoria Plzeň": "https://s1.fifaaddict.com/fo4/crests/dark/d110468.png",
  "FC Volendam": "https://s1.fifaaddict.com/fo4/crests/dark/d645.png",
  "FC Winterthur": "https://s1.fifaaddict.com/fo4/crests/dark/d1713.png",
  "FC Zürich": "https://s1.fifaaddict.com/fo4/crests/dark/d894.png",
  "FCV Dender EH": "https://s1.fifaaddict.com/fo4/crests/dark/d537.png",
  "Fenerbahçe SK": "https://s1.fifaaddict.com/fo4/crests/dark/d326.png",
  "Ferencvárosi TC": "https://s1.fifaaddict.com/fo4/crests/dark/d1874.png",
  "Feyenoord": "https://s1.fifaaddict.com/fo4/crests/dark/d246.png",
  "Fiorentina": "https://s1.fifaaddict.com/fo4/crests/dark/d110374.png",
  "FK Austria Wien": "https://s1.fifaaddict.com/fo4/crests/dark/d256.png",
  "FK Bodø/Glimt": "https://s1.fifaaddict.com/fo4/crests/dark/d918.png",
  "Football Association Champions": "https://s1.fifaaddict.com/fo4/crests/dark/d130550.png",
  "Fortuna Düsseldorf": "https://s1.fifaaddict.com/fo4/crests/dark/d110636.png",
  "Fortuna Sittard": "https://s1.fifaaddict.com/fo4/crests/dark/d634.png",
  "Free Agent": "https://s1.fifaaddict.com/fo4/crests/dark/d115653.png",
  "Frosinone": "https://s1.fifaaddict.com/fo4/crests/dark/d111657.png",
  "Fulham": "https://s1.fifaaddict.com/fo4/crests/dark/d144.png",
  "Galatasaray": "https://s1.fifaaddict.com/fo4/crests/dark/d325.png",
  "Galatasaray SK": "https://s1.fifaaddict.com/fo4/crests/dark/d325.png",
  "Gangwon FC": "https://s1.fifaaddict.com/fo4/crests/dark/d112115.png",
  "Gaziantep FK": "https://s1.fifaaddict.com/fo4/crests/dark/d110776.png",
  "Gençlerbirliği SK": "https://s1.fifaaddict.com/fo4/crests/dark/d101025.png",
  "Genoa": "https://s1.fifaaddict.com/fo4/crests/dark/d110556.png",
  "Getafe CF": "https://s1.fifaaddict.com/fo4/crests/dark/d1860.png",
  "Gil Vicente FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1888.png",
  "Gillingham": "https://s1.fifaaddict.com/fo4/crests/dark/d1802.png",
  "Gimnasia y Esgrima La Plata": "https://s1.fifaaddict.com/fo4/crests/dark/d101084.png",
  "Gimpo FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114779.png",
  "Girona FC": "https://s1.fifaaddict.com/fo4/crests/dark/d110062.png",
  "GNK Dinamo Zagreb": "https://s1.fifaaddict.com/fo4/crests/dark/d211.png",
  "Godoy Cruz": "https://s1.fifaaddict.com/fo4/crests/dark/d111706.png",
  "Golden Rookies": "https://s1.fifaaddict.com/fo4/crests/dark/d113999.png",
  "Górnik Zabrze": "https://s1.fifaaddict.com/fo4/crests/dark/d420.png",
  "Göztepe SK": "https://s1.fifaaddict.com/fo4/crests/dark/d101026.png",
  "Granada CF": "https://s1.fifaaddict.com/fo4/crests/dark/d110832.png",
  "Grasshopper Club Zürich": "https://s1.fifaaddict.com/fo4/crests/dark/d322.png",
  "Greatest Runner-Ups": "https://s1.fifaaddict.com/fo4/crests/dark/d130400.png",
  "Grenoble Foot 38": "https://s1.fifaaddict.com/fo4/crests/dark/d1805.png",
  "Gwangju FC": "https://s1.fifaaddict.com/fo4/crests/dark/d112258.png",
  "Gyeongnam FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111588.png",
  "H.O.T": "https://s1.fifaaddict.com/fo4/crests/dark/d114378.png",
  "Hamburger SV": "https://s1.fifaaddict.com/fo4/crests/dark/d28.png",
  "Hammarby IF": "https://s1.fifaaddict.com/fo4/crests/dark/d708.png",
  "Hannover 96": "https://s1.fifaaddict.com/fo4/crests/dark/d485.png",
  "Havre AC": "https://s1.fifaaddict.com/fo4/crests/dark/d1738.png",
  "Heart of Midlothian": "https://s1.fifaaddict.com/fo4/crests/dark/d80.png",
  "Hellas Verona": "https://s1.fifaaddict.com/fo4/crests/dark/d206.png",
  "Henan Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d111779.png",
  "Heracles Almelo": "https://s1.fifaaddict.com/fo4/crests/dark/d100634.png",
  "Hertha BSC": "https://s1.fifaaddict.com/fo4/crests/dark/d166.png",
  "Hibernian": "https://s1.fifaaddict.com/fo4/crests/dark/d81.png",
  "HJK Helsinki": "https://s1.fifaaddict.com/fo4/crests/dark/d100325.png",
  "HNK Hajduk Split": "https://s1.fifaaddict.com/fo4/crests/dark/d263.png",
  "Holstein Kiel": "https://s1.fifaaddict.com/fo4/crests/dark/d576.png",
  "Home Grown": "https://s1.fifaaddict.com/fo4/crests/dark/d130278.png",
  "Houston Dynamo": "https://s1.fifaaddict.com/fo4/crests/dark/d698.png",
  "Huddersfield Town": "https://s1.fifaaddict.com/fo4/crests/dark/d1939.png",
  "Hull City": "https://s1.fifaaddict.com/fo4/crests/dark/d1952.png",
  "ICON": "https://s1.fifaaddict.com/fo4/crests/dark/d112658.png",
  "ICON The Moment": "https://s1.fifaaddict.com/fo4/crests/dark/d130172.png",
  "IF Elfsborg": "https://s1.fifaaddict.com/fo4/crests/dark/d700.png",
  "IFK Göteborg": "https://s1.fifaaddict.com/fo4/crests/dark/d319.png",
  "IFK Norrköping": "https://s1.fifaaddict.com/fo4/crests/dark/d702.png",
  "İKAS Eyüpspor": "https://s1.fifaaddict.com/fo4/crests/dark/d131174.png",
  "Incheon United FC": "https://s1.fifaaddict.com/fo4/crests/dark/d110765.png",
  "Infinite Prime": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "Instituto de Córdoba": "https://s1.fifaaddict.com/fo4/crests/dark/d110953.png",
  "Inter Miami CF": "https://s1.fifaaddict.com/fo4/crests/dark/d112893.png",
  "Ipswich Town": "https://s1.fifaaddict.com/fo4/crests/dark/d94.png",
  "Istanbul Başakşehir FK": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "Jagiellonia Białystok": "https://s1.fifaaddict.com/fo4/crests/dark/d110745.png",
  "Jeju SK FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1478.png",
  "Jeonbuk Hyundai Motors FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1477.png",
  "Jeonnam Dragons": "https://s1.fifaaddict.com/fo4/crests/dark/d1475.png",
  "Journeyman": "https://s1.fifaaddict.com/fo4/crests/dark/d130303.png",
  "Juventus": "https://s1.fifaaddict.com/fo4/crests/dark/d45.png",
  "Juventus Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d130255.png",
  "KAA Gent": "https://s1.fifaaddict.com/fo4/crests/dark/d674.png",
  "Karlsruher SC": "https://s1.fifaaddict.com/fo4/crests/dark/d1832.png",
  "Kasımpaşa SK": "https://s1.fifaaddict.com/fo4/crests/dark/d111339.png",
  "Kayserispor Futbol A.Ş": "https://s1.fifaaddict.com/fo4/crests/dark/d101020.png",
  "KGHM Zagłębie Lubin": "https://s1.fifaaddict.com/fo4/crests/dark/d110749.png",
  "Kilmarnock": "https://s1.fifaaddict.com/fo4/crests/dark/d82.png",
  "Kocaelispor": "https://s1.fifaaddict.com/fo4/crests/dark/d101032.png",
  "Konyaspor": "https://s1.fifaaddict.com/fo4/crests/dark/d101033.png",
  "Korona Kielce": "https://s1.fifaaddict.com/fo4/crests/dark/d111083.png",
  "KRC Genk": "https://s1.fifaaddict.com/fo4/crests/dark/d673.png",
  "KV Kortrijk": "https://s1.fifaaddict.com/fo4/crests/dark/d100081.png",
  "KV Mechelen": "https://s1.fifaaddict.com/fo4/crests/dark/d110724.png",
  "KVC Westerlo": "https://s1.fifaaddict.com/fo4/crests/dark/d681.png",
  "LA Galaxy": "https://s1.fifaaddict.com/fo4/crests/dark/d697.png",
  "LAFC": "https://s1.fifaaddict.com/fo4/crests/dark/d112996.png",
  "Lanús": "https://s1.fifaaddict.com/fo4/crests/dark/d110395.png",
  "LASK": "https://s1.fifaaddict.com/fo4/crests/dark/d252.png",
  "Last Dance": "https://s1.fifaaddict.com/fo4/crests/dark/d130309.png",
  "Latium": "https://s1.fifaaddict.com/fo4/crests/dark/d115841.png",
  "Lecce": "https://s1.fifaaddict.com/fo4/crests/dark/d347.png",
  "Lech Poznań": "https://s1.fifaaddict.com/fo4/crests/dark/d873.png",
  "Lechia Gdańsk": "https://s1.fifaaddict.com/fo4/crests/dark/d111091.png",
  "Leeds United": "https://s1.fifaaddict.com/fo4/crests/dark/d8.png",
  "Legend of Europa": "https://s1.fifaaddict.com/fo4/crests/dark/d130461.png",
  "Legend of the Loan": "https://s1.fifaaddict.com/fo4/crests/dark/d115650.png",
  "Legendary Numbers": "https://s1.fifaaddict.com/fo4/crests/dark/d115400.png",
  "Legia Warszawa": "https://s1.fifaaddict.com/fo4/crests/dark/d1871.png",
  "Leicester City": "https://s1.fifaaddict.com/fo4/crests/dark/d95.png",
  "Levante UD": "https://s1.fifaaddict.com/fo4/crests/dark/d1853.png",
  "Leyton Orient": "https://s1.fifaaddict.com/fo4/crests/dark/d1958.png",
  "Liverpool": "https://s1.fifaaddict.com/fo4/crests/dark/d9.png",
  "Liverpool F.C. Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d114887.png",
  "Lombardia FC": "https://s1.fifaaddict.com/fo4/crests/dark/d131682.png",
  "LOSC Lille": "https://s1.fifaaddict.com/fo4/crests/dark/d65.png",
  "Loyal Heroes": "https://s1.fifaaddict.com/fo4/crests/dark/d114744.png",
  "Luton Town": "https://s1.fifaaddict.com/fo4/crests/dark/d1923.png",
  "Lyngby BK": "https://s1.fifaaddict.com/fo4/crests/dark/d15001.png",
  "Macarthur FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114604.png",
  "Málaga CF": "https://s1.fifaaddict.com/fo4/crests/dark/d573.png",
  "Malmö FF": "https://s1.fifaaddict.com/fo4/crests/dark/d320.png",
  "Manchester City": "https://s1.fifaaddict.com/fo4/crests/dark/d10.png",
  "Manchester United": "https://s1.fifaaddict.com/fo4/crests/dark/d11.png",
  "Mansfield Town": "https://s1.fifaaddict.com/fo4/crests/dark/d1940.png",
  "Medalist": "https://s1.fifaaddict.com/fo4/crests/dark/d130356.png",
  "Melbourne City": "https://s1.fifaaddict.com/fo4/crests/dark/d112224.png",
  "Melbourne Victory": "https://s1.fifaaddict.com/fo4/crests/dark/d111397.png",
  "Middlesbrough": "https://s1.fifaaddict.com/fo4/crests/dark/d12.png",
  "Milano FC": "https://s1.fifaaddict.com/fo4/crests/dark/d131681.png",
  "Millwall": "https://s1.fifaaddict.com/fo4/crests/dark/d97.png",
  "Milton Keynes Dons": "https://s1.fifaaddict.com/fo4/crests/dark/d1798.png",
  "Minnesota United FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111138.png",
  "Modena": "https://s1.fifaaddict.com/fo4/crests/dark/d1744.png",
  "Molde FK": "https://s1.fifaaddict.com/fo4/crests/dark/d417.png",
  "Moments of Glory": "https://s1.fifaaddict.com/fo4/crests/dark/d114866.png",
  "Montpellier Hérault SC": "https://s1.fifaaddict.com/fo4/crests/dark/d70.png",
  "Monza": "https://s1.fifaaddict.com/fo4/crests/dark/d111811.png",
  "Moreirense FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1900.png",
  "Motherwell": "https://s1.fifaaddict.com/fo4/crests/dark/d83.png",
  "Motor Lublin": "https://s1.fifaaddict.com/fo4/crests/dark/d111097.png",
  "Multi-League Champions": "https://s1.fifaaddict.com/fo4/crests/dark/d114889.png",
  "N.E.C. Nijmegen": "https://s1.fifaaddict.com/fo4/crests/dark/d1910.png",
  "NAC Breda": "https://s1.fifaaddict.com/fo4/crests/dark/d1904.png",
  "Nashville SC": "https://s1.fifaaddict.com/fo4/crests/dark/d114162.png",
  "Neom": "https://s1.fifaaddict.com/fo4/crests/dark/d131798.png",
  "New England Revolution": "https://s1.fifaaddict.com/fo4/crests/dark/d691.png",
  "New York City FC": "https://s1.fifaaddict.com/fo4/crests/dark/d112828.png",
  "New York Red Bulls": "https://s1.fifaaddict.com/fo4/crests/dark/d689.png",
  "Newcastle United": "https://s1.fifaaddict.com/fo4/crests/dark/d13.png",
  "Newell's Old Boys": "https://s1.fifaaddict.com/fo4/crests/dark/d110396.png",
  "NHD": "https://s1.fifaaddict.com/fo4/crests/dark/d113885.png",
  "Norwich City": "https://s1.fifaaddict.com/fo4/crests/dark/d1792.png",
  "Nostalgia": "https://s1.fifaaddict.com/fo4/crests/dark/d115416.png",
  "Nottingham Forest": "https://s1.fifaaddict.com/fo4/crests/dark/d14.png",
  "NUMBER 7": "https://s1.fifaaddict.com/fo4/crests/dark/d130459.png",
  "Odense BK": "https://s1.fifaaddict.com/fo4/crests/dark/d272.png",
  "OGC Nice": "https://s1.fifaaddict.com/fo4/crests/dark/d72.png",
  "Olympiacos": "https://s1.fifaaddict.com/fo4/crests/dark/d280.png",
  "Olympiacos FC": "https://s1.fifaaddict.com/fo4/crests/dark/d280.png",
  "Olympique de Marseille": "https://s1.fifaaddict.com/fo4/crests/dark/d219.png",
  "Olympique Lyonnais": "https://s1.fifaaddict.com/fo4/crests/dark/d66.png",
  "Orlando City Soccer Club": "https://s1.fifaaddict.com/fo4/crests/dark/d112606.png",
  "Other teams 1": "https://s1.fifaaddict.com/fo4/crests/dark/d113988.png",
  "Oud-Heverlee Leuven": "https://s1.fifaaddict.com/fo4/crests/dark/d100087.png",
  "Oxford United": "https://s1.fifaaddict.com/fo4/crests/dark/d1951.png",
  "Palermo": "https://s1.fifaaddict.com/fo4/crests/dark/d1843.png",
  "Panathinaikos": "https://s1.fifaaddict.com/fo4/crests/dark/d1884.png",
  "Panathinaikos FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1884.png",
  "PAOK FC": "https://s1.fifaaddict.com/fo4/crests/dark/d393.png",
  "Paris FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111817.png",
  "Paris Saint-Germain": "https://s1.fifaaddict.com/fo4/crests/dark/d73.png",
  "Parma": "https://s1.fifaaddict.com/fo4/crests/dark/d50.png",
  "Pau FC": "https://s1.fifaaddict.com/fo4/crests/dark/d110321.png",
  "PEC Zwolle": "https://s1.fifaaddict.com/fo4/crests/dark/d1914.png",
  "Perth Glory": "https://s1.fifaaddict.com/fo4/crests/dark/d111399.png",
  "Pescara Calcio": "https://s1.fifaaddict.com/fo4/crests/dark/d200.png",
  "Philadelphia Union": "https://s1.fifaaddict.com/fo4/crests/dark/d112134.png",
  "Piast Gliwice": "https://s1.fifaaddict.com/fo4/crests/dark/d111086.png",
  "Pisa": "https://s1.fifaaddict.com/fo4/crests/dark/d110738.png",
  "Plymouth Argyle": "https://s1.fifaaddict.com/fo4/crests/dark/d1929.png",
  "Pogoń Szczecin": "https://s1.fifaaddict.com/fo4/crests/dark/d110746.png",
  "Portland Timbers": "https://s1.fifaaddict.com/fo4/crests/dark/d111140.png",
  "Preston North End": "https://s1.fifaaddict.com/fo4/crests/dark/d1801.png",
  "Prime": "https://s1.fifaaddict.com/fo4/crests/dark/d130465.png",
  "PSV": "https://s1.fifaaddict.com/fo4/crests/dark/d247.png",
  "Qarabağ FK": "https://s1.fifaaddict.com/fo4/crests/dark/d113888.png",
  "Qingdao Hainiu Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d131173.png",
  "Qingdao West Coast FC": "https://s1.fifaaddict.com/fo4/crests/dark/d131488.png",
  "Queens Park Rangers": "https://s1.fifaaddict.com/fo4/crests/dark/d15.png",
  "Racing Club": "https://s1.fifaaddict.com/fo4/crests/dark/d101085.png",
  "Racing de Ferrol": "https://s1.fifaaddict.com/fo4/crests/dark/d110242.png",
  "RAMS Başakşehir": "https://s1.fifaaddict.com/fo4/crests/dark/d101014.png",
  "Rangers": "https://s1.fifaaddict.com/fo4/crests/dark/d86.png",
  "Rayo Vallecano": "https://s1.fifaaddict.com/fo4/crests/dark/d480.png",
  "RB Leipzig": "https://s1.fifaaddict.com/fo4/crests/dark/d112172.png",
  "RC Deportivo": "https://s1.fifaaddict.com/fo4/crests/dark/d242.png",
  "RC Lens": "https://s1.fifaaddict.com/fo4/crests/dark/d64.png",
  "RC Strasbourg Alsace": "https://s1.fifaaddict.com/fo4/crests/dark/d76.png",
  "RCD Espanyol de Barcelona": "https://s1.fifaaddict.com/fo4/crests/dark/d452.png",
  "RCD Mallorca": "https://s1.fifaaddict.com/fo4/crests/dark/d453.png",
  "Reading": "https://s1.fifaaddict.com/fo4/crests/dark/d1793.png",
  "Real Betis Balompié": "https://s1.fifaaddict.com/fo4/crests/dark/d449.png",
  "Real Club Celta de Vigo": "https://s1.fifaaddict.com/fo4/crests/dark/d450.png",
  "Real Madrid": "https://s1.fifaaddict.com/fo4/crests/dark/d243.png",
  "Real Madrid Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d115366.png",
  "Real Oviedo": "https://s1.fifaaddict.com/fo4/crests/dark/d110827.png",
  "Real Racing Club": "https://s1.fifaaddict.com/fo4/crests/dark/d456.png",
  "Real Salt Lake": "https://s1.fifaaddict.com/fo4/crests/dark/d111065.png",
  "Real Sociedad": "https://s1.fifaaddict.com/fo4/crests/dark/d457.png",
  "Real Sporting": "https://s1.fifaaddict.com/fo4/crests/dark/d459.png",
  "Real Valladolid CF": "https://s1.fifaaddict.com/fo4/crests/dark/d462.png",
  "Real Zaragoza": "https://s1.fifaaddict.com/fo4/crests/dark/d244.png",
  "Red Star FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111273.png",
  "Reggiana": "https://s1.fifaaddict.com/fo4/crests/dark/d110740.png",
  "Returnees": "https://s1.fifaaddict.com/fo4/crests/dark/d130279.png",
  "Rio Ave FC": "https://s1.fifaaddict.com/fo4/crests/dark/d744.png",
  "River Plate": "https://s1.fifaaddict.com/fo4/crests/dark/d1876.png",
  "RKC Waalwijk": "https://s1.fifaaddict.com/fo4/crests/dark/d1905.png",
  "RKS Radomiak Radom": "https://s1.fifaaddict.com/fo4/crests/dark/d111088.png",
  "RKS Raków Częstochowa": "https://s1.fifaaddict.com/fo4/crests/dark/d114326.png",
  "Rodez Aveyron Football": "https://s1.fifaaddict.com/fo4/crests/dark/d111659.png",
  "Rosario Central": "https://s1.fifaaddict.com/fo4/crests/dark/d110580.png",
  "Rosenborg BK": "https://s1.fifaaddict.com/fo4/crests/dark/d298.png",
  "Rot-Weiss Essen": "https://s1.fifaaddict.com/fo4/crests/dark/d526.png",
  "Royal Antwerp FC": "https://s1.fifaaddict.com/fo4/crests/dark/d230.png",
  "Royale Union Saint-Gilloise": "https://s1.fifaaddict.com/fo4/crests/dark/d2014.png",
  "RSC Anderlecht": "https://s1.fifaaddict.com/fo4/crests/dark/d229.png",
  "RTS Widzew Łódź": "https://s1.fifaaddict.com/fo4/crests/dark/d301.png",
  "RZ Pellets Wolfsberger AC": "https://s1.fifaaddict.com/fo4/crests/dark/d111822.png",
  "S.S. Juve Stabia 1907": "https://s1.fifaaddict.com/fo4/crests/dark/d112124.png",
  "Salernitana": "https://s1.fifaaddict.com/fo4/crests/dark/d110373.png",
  "Salford City": "https://s1.fifaaddict.com/fo4/crests/dark/d113926.png",
  "Sampdoria": "https://s1.fifaaddict.com/fo4/crests/dark/d1837.png",
  "Samsunspor A.Ş": "https://s1.fifaaddict.com/fo4/crests/dark/d748.png",
  "San Diego FC": "https://s1.fifaaddict.com/fo4/crests/dark/d131439.png",
  "San Jose Earthquakes": "https://s1.fifaaddict.com/fo4/crests/dark/d111928.png",
  "San Lorenzo de Almagro": "https://s1.fifaaddict.com/fo4/crests/dark/d1013.png",
  "Santa Clara": "https://s1.fifaaddict.com/fo4/crests/dark/d1438.png",
  "Sarpsborg 08": "https://s1.fifaaddict.com/fo4/crests/dark/d112199.png",
  "Sassuolo": "https://s1.fifaaddict.com/fo4/crests/dark/d111974.png",
  "SC Bastia": "https://s1.fifaaddict.com/fo4/crests/dark/d58.png",
  "SC Braga": "https://s1.fifaaddict.com/fo4/crests/dark/d1896.png",
  "SC Farense": "https://s1.fifaaddict.com/fo4/crests/dark/d489.png",
  "sc Heerenveen": "https://s1.fifaaddict.com/fo4/crests/dark/d1913.png",
  "SC Paderborn 07": "https://s1.fifaaddict.com/fo4/crests/dark/d10030.png",
  "SC Preußen Münster": "https://s1.fifaaddict.com/fo4/crests/dark/d531.png",
  "SC Rheindorf Altach": "https://s1.fifaaddict.com/fo4/crests/dark/d15009.png",
  "SD Eibar": "https://s1.fifaaddict.com/fo4/crests/dark/d467.png",
  "SD Huesca": "https://s1.fifaaddict.com/fo4/crests/dark/d110839.png",
  "Seattle Sounders FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111144.png",
  "Seoul E-Land FC": "https://s1.fifaaddict.com/fo4/crests/dark/d113031.png",
  "Servette FC": "https://s1.fifaaddict.com/fo4/crests/dark/d324.png",
  "Sevilla FC": "https://s1.fifaaddict.com/fo4/crests/dark/d481.png",
  "Shakhtar Donetsk": "https://s1.fifaaddict.com/fo4/crests/dark/d101059.png",
  "Shamrock Rovers": "https://s1.fifaaddict.com/fo4/crests/dark/d306.png",
  "Shandong Taishan Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d111724.png",
  "Shanghai Port Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d112540.png",
  "Shanghai Shenhua Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d110955.png",
  "Sheffield United": "https://s1.fifaaddict.com/fo4/crests/dark/d1794.png",
  "Sheffield Wednesday": "https://s1.fifaaddict.com/fo4/crests/dark/d1807.png",
  "Shenzhen Peng City": "https://s1.fifaaddict.com/fo4/crests/dark/d131487.png",
  "Sint-Truidense VV": "https://s1.fifaaddict.com/fo4/crests/dark/d680.png",
  "Sipay Bodrum FK": "https://s1.fifaaddict.com/fo4/crests/dark/d131388.png",
  "SK Austria Klagenfurt": "https://s1.fifaaddict.com/fo4/crests/dark/d1787.png",
  "SK Rapid": "https://s1.fifaaddict.com/fo4/crests/dark/d254.png",
  "SK Slavia Praha": "https://s1.fifaaddict.com/fo4/crests/dark/d266.png",
  "SK Sturm Graz": "https://s1.fifaaddict.com/fo4/crests/dark/d209.png",
  "SL Benfica": "https://s1.fifaaddict.com/fo4/crests/dark/d234.png",
  "Sønderjyske Fodbold": "https://s1.fifaaddict.com/fo4/crests/dark/d1447.png",
  "Southampton": "https://s1.fifaaddict.com/fo4/crests/dark/d17.png",
  "Sparta Rotterdam": "https://s1.fifaaddict.com/fo4/crests/dark/d100646.png",
  "Spezia": "https://s1.fifaaddict.com/fo4/crests/dark/d113974.png",
  "Sport-Club Freiburg": "https://s1.fifaaddict.com/fo4/crests/dark/d25.png",
  "Sporting Charleroi": "https://s1.fifaaddict.com/fo4/crests/dark/d670.png",
  "Sporting CP": "https://s1.fifaaddict.com/fo4/crests/dark/d237.png",
  "Sporting Kansas City": "https://s1.fifaaddict.com/fo4/crests/dark/d696.png",
  "Spotlight": "https://s1.fifaaddict.com/fo4/crests/dark/d115404.png",
  "SpVgg Greuther Fürth": "https://s1.fifaaddict.com/fo4/crests/dark/d165.png",
  "SSC Napoli": "https://s1.fifaaddict.com/fo4/crests/dark/d48.png",
  "St. Louis CITY SC": "https://s1.fifaaddict.com/fo4/crests/dark/d113018.png",
  "Stade Brestois 29": "https://s1.fifaaddict.com/fo4/crests/dark/d378.png",
  "Stade de Reims": "https://s1.fifaaddict.com/fo4/crests/dark/d379.png",
  "Stade Lavallois MFC": "https://s1.fifaaddict.com/fo4/crests/dark/d1814.png",
  "Stade Malherbe Caen": "https://s1.fifaaddict.com/fo4/crests/dark/d210.png",
  "Stade Rennais FC": "https://s1.fifaaddict.com/fo4/crests/dark/d74.png",
  "Standard de Liège": "https://s1.fifaaddict.com/fo4/crests/dark/d232.png",
  "Standard Liège": "https://s1.fifaaddict.com/fo4/crests/dark/d232.png",
  "Stockport County": "https://s1.fifaaddict.com/fo4/crests/dark/d1931.png",
  "Stoke City": "https://s1.fifaaddict.com/fo4/crests/dark/d1806.png",
  "Südtirol": "https://s1.fifaaddict.com/fo4/crests/dark/d112494.png",
  "Sunderland": "https://s1.fifaaddict.com/fo4/crests/dark/d106.png",
  "Suwon FC": "https://s1.fifaaddict.com/fo4/crests/dark/d112558.png",
  "Suwon Samsung Bluewings": "https://s1.fifaaddict.com/fo4/crests/dark/d983.png",
  "SV Darmstadt 98": "https://s1.fifaaddict.com/fo4/crests/dark/d110502.png",
  "SV Sandhausen": "https://s1.fifaaddict.com/fo4/crests/dark/d110178.png",
  "SV Werder Bremen": "https://s1.fifaaddict.com/fo4/crests/dark/d38.png",
  "Swansea City": "https://s1.fifaaddict.com/fo4/crests/dark/d1960.png",
  "Swindon Town": "https://s1.fifaaddict.com/fo4/crests/dark/d1934.png",
  "Sydney FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111400.png",
  "Tianjin Jinmen Tiger Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d111774.png",
  "Top Transfer": "https://s1.fifaaddict.com/fo4/crests/dark/d113979.png",
  "Torino": "https://s1.fifaaddict.com/fo4/crests/dark/d54.png",
  "Toronto FC": "https://s1.fifaaddict.com/fo4/crests/dark/d111651.png",
  "Tottenham Hotspur": "https://s1.fifaaddict.com/fo4/crests/dark/d18.png",
  "Toulouse FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1809.png",
  "Tournament Best": "https://s1.fifaaddict.com/fo4/crests/dark/d113956.png",
  "Tournament Champions": "https://s1.fifaaddict.com/fo4/crests/dark/d114155.png",
  "Trabzonspor": "https://s1.fifaaddict.com/fo4/crests/dark/d436.png",
  "TSG Hoffenheim": "https://s1.fifaaddict.com/fo4/crests/dark/d10029.png",
  "TSV 1860 München": "https://s1.fifaaddict.com/fo4/crests/dark/d33.png",
  "UD Almería": "https://s1.fifaaddict.com/fo4/crests/dark/d1861.png",
  "UD Las Palmas": "https://s1.fifaaddict.com/fo4/crests/dark/d472.png",
  "Udinese": "https://s1.fifaaddict.com/fo4/crests/dark/d55.png",
  "UEFA EURO 2024": "https://s1.fifaaddict.com/fo4/crests/dark/d130589.png",
  "Ulsan HD FC": "https://s1.fifaaddict.com/fo4/crests/dark/d1473.png",
  "Unexpected Transfer": "https://s1.fifaaddict.com/fo4/crests/dark/d130304.png",
  "Unión de Santa Fe": "https://s1.fifaaddict.com/fo4/crests/dark/d111716.png",
  "Unsung Players": "https://s1.fifaaddict.com/fo4/crests/dark/d115342.png",
  "US Boulogne CO": "https://s1.fifaaddict.com/fo4/crests/dark/d132680.png",
  "USL Dunkerque": "https://s1.fifaaddict.com/fo4/crests/dark/d111276.png",
  "Valencia CF": "https://s1.fifaaddict.com/fo4/crests/dark/d461.png",
  "Vancouver Whitecaps FC": "https://s1.fifaaddict.com/fo4/crests/dark/d101112.png",
  "Vejle Boldklub": "https://s1.fifaaddict.com/fo4/crests/dark/d822.png",
  "Vélez Sarsfield": "https://s1.fifaaddict.com/fo4/crests/dark/d101088.png",
  "Venezia": "https://s1.fifaaddict.com/fo4/crests/dark/d205.png",
  "Veteran": "https://s1.fifaaddict.com/fo4/crests/dark/d114878.png",
  "VfB Stuttgart": "https://s1.fifaaddict.com/fo4/crests/dark/d36.png",
  "VfL Bochum 1848": "https://s1.fifaaddict.com/fo4/crests/dark/d160.png",
  "VfL Wolfsburg": "https://s1.fifaaddict.com/fo4/crests/dark/d175.png",
  "Viet Nam": "https://s1.fifaaddict.com/fo4/crests/dark/d113666.png",
  "Vietnam Future Generation": "https://s1.fifaaddict.com/fo4/crests/dark/d130173.png",
  "Villarreal CF": "https://s1.fifaaddict.com/fo4/crests/dark/d483.png",
  "Vitória SC": "https://s1.fifaaddict.com/fo4/crests/dark/d1887.png",
  "VN Best": "https://s1.fifaaddict.com/fo4/crests/dark/d115631.png",
  "VN Legend": "https://s1.fifaaddict.com/fo4/crests/dark/d115424.png",
  "Volta Live Ambassador": "https://s1.fifaaddict.com/fo4/crests/dark/d114868.png",
  "Walsall": "https://s1.fifaaddict.com/fo4/crests/dark/d1803.png",
  "Warriors of Glory": "https://s1.fifaaddict.com/fo4/crests/dark/d130586.png",
  "Watford": "https://s1.fifaaddict.com/fo4/crests/dark/d1795.png",
  "Wellington Phoenix": "https://s1.fifaaddict.com/fo4/crests/dark/d111766.png",
  "West Bromwich Albion": "https://s1.fifaaddict.com/fo4/crests/dark/d109.png",
  "West Ham United": "https://s1.fifaaddict.com/fo4/crests/dark/d19.png",
  "Western Sydney Wanderers": "https://s1.fifaaddict.com/fo4/crests/dark/d112427.png",
  "Western United FC": "https://s1.fifaaddict.com/fo4/crests/dark/d114023.png",
  "Wigan Athletic": "https://s1.fifaaddict.com/fo4/crests/dark/d1917.png",
  "Willem II": "https://s1.fifaaddict.com/fo4/crests/dark/d1907.png",
  "Winning Streak": "https://s1.fifaaddict.com/fo4/crests/dark/d130493.png",
  "Wisła Płock": "https://s1.fifaaddict.com/fo4/crests/dark/d1569.png",
  "Wolverhampton Wanderers": "https://s1.fifaaddict.com/fo4/crests/dark/d110.png",
  "Wonderboys": "https://s1.fifaaddict.com/fo4/crests/dark/d130446.png",
  "World Cup 2022": "https://s1.fifaaddict.com/fo4/crests/dark/d130182.png",
  "Wrexham": "https://s1.fifaaddict.com/fo4/crests/dark/d1947.png",
  "WSG Tirol": "https://s1.fifaaddict.com/fo4/crests/dark/d15040.png",
  "Wuhan Three Towns Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d116361.png",
  "Yunnan Yukun Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d131531.png",
  "Zhejiang Professional Football Club": "https://s1.fifaaddict.com/fo4/crests/dark/d112163.png"
};

export function getNationFlag(nation) {
  return NATION_FLAGS[nation] || '';
}

export function getLeagueLogo(league) {
  return LEAGUE_LOGOS[league] || '';
}

export function getClubCrest(club) {
  return CLUB_CRESTS[club] || '';
}
