export const TRAINING_POSITIONS = {
  'LS/ST/RS': [
    { name: 'Dứt điểm', coefficient: 18 },
    { name: 'Chọn vị trí', coefficient: 13 },
    { name: 'Giữ bóng', coefficient: 10 },
    { name: 'Lực sút', coefficient: 10 },
    { name: 'Đánh đầu', coefficient: 10 },
    { name: 'Phản ứng', coefficient: 8 },
    { name: 'Rê bóng', coefficient: 7 },
    { name: 'Sức mạnh', coefficient: 5 },
    { name: 'Tốc độ', coefficient: 5 },
    { name: 'Chuyền ngắn', coefficient: 5 },
    { name: 'Tăng tốc', coefficient: 4 },
    { name: 'Sút xa', coefficient: 3 },
    { name: 'Vô lê', coefficient: 2 },
  ],
  'LF/CF/RF': [
    { name: 'Giữ bóng', coefficient: 15 },
    { name: 'Rê bóng', coefficient: 14 },
    { name: 'Chọn vị trí', coefficient: 13 },
    { name: 'Dứt điểm', coefficient: 11 },
    { name: 'Phản ứng', coefficient: 9 },
    { name: 'Chuyền ngắn', coefficient: 9 },
    { name: 'Tầm nhìn', coefficient: 8 },
    { name: 'Lực sút', coefficient: 5 },
    { name: 'Tốc độ', coefficient: 5 },
    { name: 'Tăng tốc', coefficient: 5 },
    { name: 'Sút xa', coefficient: 4 },
    { name: 'Đánh đầu', coefficient: 2 },
  ],
  'RW/LW': [
    { name: 'Rê bóng', coefficient: 16 },
    { name: 'Giữ bóng', coefficient: 14 },
    { name: 'Dứt điểm', coefficient: 10 },
    { name: 'Chọn vị trí', coefficient: 9 },
    { name: 'Chuyền ngắn', coefficient: 9 },
    { name: 'Tạt bóng', coefficient: 9 },
    { name: 'Phản ứng', coefficient: 7 },
    { name: 'Tăng tốc', coefficient: 7 },
    { name: 'Tầm nhìn', coefficient: 6 },
    { name: 'Tốc độ', coefficient: 6 },
    { name: 'Sút xa', coefficient: 4 },
    { name: 'Khéo léo', coefficient: 3 },
  ],
  'LAM/CAM/RAM': [
    { name: 'Chuyền ngắn', coefficient: 16 },
    { name: 'Giữ bóng', coefficient: 15 },
    { name: 'Tầm nhìn', coefficient: 14 },
    { name: 'Rê bóng', coefficient: 13 },
    { name: 'Chọn vị trí', coefficient: 9 },
    { name: 'Phản ứng', coefficient: 7 },
    { name: 'Dứt điểm', coefficient: 7 },
    { name: 'Sút xa', coefficient: 5 },
    { name: 'Tăng tốc', coefficient: 4 },
    { name: 'Chuyền dài', coefficient: 4 },
    { name: 'Tốc độ', coefficient: 3 },
    { name: 'Khéo léo', coefficient: 3 },
  ],
  'RM/LM': [
    { name: 'Rê bóng', coefficient: 15 },
    { name: 'Giữ bóng', coefficient: 13 },
    { name: 'Chuyền ngắn', coefficient: 11 },
    { name: 'Tạt bóng', coefficient: 10 },
    { name: 'Chọn vị trí', coefficient: 8 },
    { name: 'Phản ứng', coefficient: 7 },
    { name: 'Tăng tốc', coefficient: 7 },
    { name: 'Tầm nhìn', coefficient: 7 },
    { name: 'Dứt điểm', coefficient: 6 },
    { name: 'Tốc độ', coefficient: 6 },
    { name: 'Thể lực', coefficient: 5 },
    { name: 'Chuyền dài', coefficient: 5 },
  ],
  'LCM/CM/RCM': [
    { name: 'Chuyền ngắn', coefficient: 17 },
    { name: 'Giữ bóng', coefficient: 14 },
    { name: 'Tầm nhìn', coefficient: 13 },
    { name: 'Chuyền dài', coefficient: 13 },
    { name: 'Phản ứng', coefficient: 8 },
    { name: 'Rê bóng', coefficient: 7 },
    { name: 'Chọn vị trí', coefficient: 6 },
    { name: 'Thể lực', coefficient: 6 },
    { name: 'Lấy bóng', coefficient: 5 },
    { name: 'Cắt bóng', coefficient: 5 },
    { name: 'Sút xa', coefficient: 4 },
    { name: 'Dứt điểm', coefficient: 2 },
  ],
  'LDM/CDM/RDM': [
    { name: 'Chuyền ngắn', coefficient: 14 },
    { name: 'Cắt bóng', coefficient: 14 },
    { name: 'Lấy bóng', coefficient: 12 },
    { name: 'Giữ bóng', coefficient: 10 },
    { name: 'Chuyền dài', coefficient: 10 },
    { name: 'Kèm người', coefficient: 9 },
    { name: 'Phản ứng', coefficient: 7 },
    { name: 'Thể lực', coefficient: 6 },
    { name: 'Xoạc bóng', coefficient: 5 },
    { name: 'Quyết đoán', coefficient: 5 },
    { name: 'Tầm nhìn', coefficient: 4 },
    { name: 'Sức mạnh', coefficient: 4 },
  ],
  'LB/RB': [
    { name: 'Xoạc bóng', coefficient: 14 },
    { name: 'Cắt bóng', coefficient: 12 },
    { name: 'Lấy bóng', coefficient: 11 },
    { name: 'Tạt bóng', coefficient: 9 },
    { name: 'Thể lực', coefficient: 8 },
    { name: 'Phản ứng', coefficient: 8 },
    { name: 'Kèm người', coefficient: 8 },
    { name: 'Chuyền ngắn', coefficient: 7 },
    { name: 'Giữ bóng', coefficient: 7 },
    { name: 'Tốc độ', coefficient: 7 },
    { name: 'Tăng tốc', coefficient: 5 },
    { name: 'Đánh đầu', coefficient: 4 },
  ],
  'LWB/RWB': [
    { name: 'Cắt bóng', coefficient: 12 },
    { name: 'Tạt bóng', coefficient: 12 },
    { name: 'Xoạc bóng', coefficient: 11 },
    { name: 'Chuyền ngắn', coefficient: 10 },
    { name: 'Thể lực', coefficient: 10 },
    { name: 'Lấy bóng', coefficient: 8 },
    { name: 'Giữ bóng', coefficient: 8 },
    { name: 'Phản ứng', coefficient: 8 },
    { name: 'Kèm người', coefficient: 7 },
    { name: 'Tốc độ', coefficient: 6 },
    { name: 'Rê bóng', coefficient: 4 },
    { name: 'Tăng tốc', coefficient: 4 },
  ],
  'CB': [
    { name: 'Lấy bóng', coefficient: 17 },
    { name: 'Kèm người', coefficient: 14 },
    { name: 'Cắt bóng', coefficient: 13 },
    { name: 'Xoạc bóng', coefficient: 10 },
    { name: 'Đánh đầu', coefficient: 10 },
    { name: 'Sức mạnh', coefficient: 10 },
    { name: 'Quyết đoán', coefficient: 7 },
    { name: 'Phản ứng', coefficient: 5 },
    { name: 'Chuyền ngắn', coefficient: 5 },
    { name: 'Giữ bóng', coefficient: 4 },
    { name: 'Nhảy', coefficient: 3 },
    { name: 'Tốc độ', coefficient: 2 },
  ],
  'SW': [
    { name: 'Xoạc bóng', coefficient: 15 },
    { name: 'Kèm người', coefficient: 15 },
    { name: 'Lấy bóng', coefficient: 15 },
    { name: 'Đánh đầu', coefficient: 10 },
    { name: 'Sức mạnh', coefficient: 10 },
    { name: 'Quyết đoán', coefficient: 8 },
    { name: 'Phản ứng', coefficient: 8 },
    { name: 'Chuyền ngắn', coefficient: 5 },
    { name: 'Giữ bóng', coefficient: 5 },
    { name: 'Nhảy', coefficient: 5 },
    { name: 'Rê bóng', coefficient: 4 },
  ],
  'GK': [
    { name: 'Đổ người', coefficient: 21, gk: true },
    { name: 'Bắt bóng', coefficient: 21, gk: true },
    { name: 'Chọn vị trí', coefficient: 21, gk: true },
    { name: 'Phản xạ', coefficient: 21, gk: true },
    { name: 'Phản ứng', coefficient: 11 },
    { name: 'Phát bóng', coefficient: 5, gk: true },
  ],
};

const POSITION_TO_GROUP = {
  ST: 'LS/ST/RS', LS: 'LS/ST/RS', RS: 'LS/ST/RS',
  CF: 'LF/CF/RF', LF: 'LF/CF/RF', RF: 'LF/CF/RF',
  RW: 'RW/LW', LW: 'RW/LW',
  CAM: 'LAM/CAM/RAM', LAM: 'LAM/CAM/RAM', RAM: 'LAM/CAM/RAM',
  RM: 'RM/LM', LM: 'RM/LM',
  CM: 'LCM/CM/RCM',
  CDM: 'LDM/CDM/RDM',
  LB: 'LB/RB', RB: 'LB/RB',
  LWB: 'LWB/RWB', RWB: 'LWB/RWB',
  CB: 'CB',
  SW: 'SW',
  GK: 'GK',
};

const STAT_NAME_TO_LABEL = {
  'Chuyền ngắn': 'Ch.ngắn',
  'Chuyền dài': 'Ch.dài',
  'Vô lê': 'Vô-lê',
  'Lấy bóng': 'Lắy bóng',
};

export function getTrainingStats(positionCode) {
  const group = POSITION_TO_GROUP[positionCode];
  if (!group) return null;
  const stats = TRAINING_POSITIONS[group];
  return stats.map(({ name, coefficient, gk }) => {
    const rawLabel = STAT_NAME_TO_LABEL[name] || name;
    const statKey = gk ? `gk:${name}` : rawLabel;
    return { name, coefficient, statKey };
  });
}
